FROM ubuntu:18.04

RUN apt-get update
RUN apt-get install -y python3 python3-pip
RUN apt-get install -y vim
RUN apt-get install -y netcat iproute2 iputils-ping

COPY ./requirements.txt /tmp/requirements.txt

RUN pip3 install -r /tmp/requirements.txt

RUN apt-get install -y iproute2 tcpdump